GET http://localhost:3001/api/persons/

###
DELETE http://localhost:3001/api/persons/2394

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Jukka Palmu",
    "number": "0100 100 100"
}
###