GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "A Jukka Palmu",
    "number": "0100 100 100"
}
###
GET https://fso-phone-jani.herokuapp.com/api/persons/

###
DELETE https://fso-phone-jani.herokuapp.com/api/persons/4

###
POST https://fso-phone-jani.herokuapp.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "A Jukka Palmu",
    "number": "0100 100 100"
}
###